version: '3.8'

x-services-volume:
  &services-volume
  type: bind
  source: ./
  target: /var/


services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    restart: always
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_home/:/var/jenkins_home
    environment:
      - GIT_SSL_NO_VERIFY=true
    restart: always
  agent:
    build:
      context: .
      dockerfile: agentDockerfile
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - GIT_SSL_NO_VERIFY=true
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDETfGzA4XH/ha1g9O/XgqCDrIfDRXzwJmgah5DkmahUoITV5aBH5koB+aeCtozppipHwqu+qxMoFN9OVFFa/6wuZUxjcVIZF+hW/Opzr/6RsSglEXm9L/Dz1AdsnATf3XHjF4Grv9hv1n5ldSZV4cY5F1uqskcFIT5OK0m+e+CBRRzeXYjoXED67MPGaL3fsPL3zo6KZd70q+FxSfMuTrDFW9mZNHTbldF8gxiyS7+8leCLGnlqkZcWT8+EPC6G8qi4W/dKjmse3zq8NCC2iLb2Zk4dF1lA0ImCQGrfGwbCwyAFez23vIXyiI3UMGNXOdz4yIcGJ/STkQPhOKdXaNI8vPs4V5cITjgVIACJOS1D7/OSNaL9JUqBu86BRXwiE6H8I/7Xk0XjL3oi/iyShuKyb2RzVrFBdQoDpyziCJ0Pi2D2MCdxA9/EZy2HJMNDXknErf0TFsaL/+ZN5vM6Rr/qggON/mSO334FkinBlgbsJh4Q9LarfuWFjMYnepiSbc= jenkins@8fab23d94242
    volumes: 
      - *services-volume
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  simpleweb:
    build:
      context: .
      dockerfile: simplewebDockerfile
    user: root
    ports:
      - "1555:1555"
    container_name: simpleweb
    volumes:
      - *services-volume
      - ./appdata/:/var/appdata
    command: bash -c "
      python3 /var/appdata/simpleweb-main/app.py"
    tty: true
    restart: always
    environment:
      - DB_PROVIDER=mssql+pyodbc
      - DB_USER=sa
      - DB_PASSWORD=PLC_%40ccess_test_1
      - DB_SERVER=ILYA
      - DB_PORT=1433
      - DB_DBNAME=msdb
      - DB_DRIVER=ODBC+Driver+18+for+SQL+Server
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mssql_data/data:/var/opt/mssql/data
      - ./mssql_data/log:/var/opt/mssql/log 
      - ./mssql_data/secrets:/var/opt/mssql/secrets
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PLC_@ccess_test_1